### ISSUE TITLE
Have anyone successfully implemented it using bluestacks ? Please share your knowledge.. i would like to know how to handle the proxy

### ISSUE THREAD

**Issue by subashiglesias** [rastapasta/pokemon-go-mitm-node#102]
I'm totally new... Tried proxycap, it refuses connection. I gave public IP, didn't work. gave my lap (Linux) and used proxy cap on windows (Bluestacks), didn't work.. Connected my linux wit ethernet and used it as hotspot for windows, didn't work... Am i doing it right ?

**Comment by darkoulis12** [comment]
i got same problem with virtual machine installed ubuntu and i use nox...i hope some1 gonna help us

**Comment by subashiglesias** [comment]
Agreed mate... Let's just wait... Where are u stuck ?

**Comment by darkoulis12** [comment]
i do evrything im in last part (i must set port) 

if you want help (to help each other and try to found solutions) send me message at paleokwstas89@gmail.com with your skype or with your fb

**Comment by jmoriau** [comment]
Yes please continue this somewhere else issues are not a support forum, please close this.

**Comment by subashiglesias** [comment]
I found the solution.. I'll close this
