### ISSUE TITLE
'Request' is not in npm registry.

### ISSUE THREAD

**Issue by senacandrampc** [rastapasta/pokemon-go-mitm-node#105]
When I do _npm install_ I got this error

> npm ERR! 404 'request' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, or http url, or git url.
>
> npm ERR! System Linux 3.4.0+
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! cwd /mnt/c/Projects/pokemon-go-mitm-node
> npm ERR! node -v v0.10.25
> npm ERR! npm -v 1.3.10
> #npm ERR! code E404

Running _coffee example.logTraffic.coffee_ then results _Error: Module did not self-register._

Any way to solve this? Thanks.

**Comment by rastapasta** [comment]
You have to update your node & npm installation - its verrry outdated :)
https://www.npmjs.com/package/request is def. present
