### ISSUE TITLE
Proxy PROBLEM !

### ISSUE THREAD

**Issue by alex3604** [rastapasta/pokemon-go-mitm-node#106]
Can someone help me to set the proxy for Pokemon GO MITM please ? I don't know what i got to do. I'm using ubuntu. I've already set all, just don't know what to do to setup proxy

**Comment by caspaas** [comment]
On your phone.
You need to connect your phone, through your laptop.

**Comment by alex3604** [comment]
@caspaas How ? Please, show me how

**Comment by architjn** [comment]
Yes i want to know it too @caspaas

**Comment by rastapasta** [comment]
@alex3604 @architjn 
http://www.digitalcitizen.life/how-add-proxy-server-wireless-connection-android
