### ISSUE TITLE
Certificate missing on ubuntu

### ISSUE THREAD

**Issue by Miky94x** [rastapasta/pokemon-go-mitm-node#109]
Hi, thanks for the great work but i have a problem, when i run `coffee example.logTraffic.coffee` without error and i close the terminal, i don't have any location named `.http-mitm-proxy/certs/ca.pem`
Where cai i found it?
Thanks

**Comment by Poootaatoooo** [comment]
press CTRL+H to unhide the folder, and it'll be in the pokemon-go-mitm folder

**Comment by Miky94x** [comment]
thanks :smile: 
have a good day
