### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by architjn** [rastapasta/pokemon-go-mitm-node#113]
I ran the code and all is working
but when i change port on my device i get login error on pokemon go
so what i did is stopped the script and logged in and then reran the script
and nothing was happening on the screen, it was all normal

I tried many examples (visitPokestop and others)
For proxy hostname i added my laptop's local ip address
and port to 8081

**Comment by Poootaatoooo** [comment]
did you add the certificate and install the xposed module? (and btw nothing happens on the screen either way)

**Comment by Poootaatoooo** [comment]
and are you using the system settings to set the proxy, or using an external app like proxydroid?

**Comment by architjn** [comment]
yes added certificate and applied xposed
and does it matter i am using certificate which was 1st created and never updated after

using system settings

**Comment by architjn** [comment]
and won't visitPokestop should make our character move or shouldn't it do some activity on screen?

**Comment by Poootaatoooo** [comment]
it doesnt show any activity in the terminal, and the pokestop scripts need you to actually go to a pokestop

**Comment by architjn** [comment]
thanks changeLevel Worked

**Comment by Poootaatoooo** [comment]
no problem!
