### ISSUE TITLE
Question Proxy Machine

### ISSUE THREAD

**Issue by unrealshape** [rastapasta/pokemon-go-mitm-node#114]
Hello.

I have the following problem by Pokemongo MITM  ..
I complete all Steps from guide only the last one : "Setup your connection to use your machine as a proxy (default port is 8081)"
I do not understand this step.
Can you maybe give some tips to solve that?
(i´ll try with charlesproxy & squid but no way to solve that-.-)

greeting
unrealshape

**Comment by Poootaatoooo** [comment]
you dont have to do anything on your machine, if you're on android, go to your wifi settings, long press your network, tap modify, change proxy to manual, and in hostname put your machine's local ip address, and in port put 8081, and you should be set

**Comment by unrealshape** [comment]
wow i will try now restart to linux

**Comment by unrealshape** [comment]
hey
I use an iPhone and have ilendemli patch installed via Terminal.
Now I have set the WLAN connection via proxy, it froze in the loading window(garados with attention).
Do you have an idea?

**Comment by unrealshape** [comment]
close im done
