### ISSUE TITLE
Only client->server requests get through

### ISSUE THREAD

**Issue by ELynx** [rastapasta/pokemon-go-mitm-node#116]
Installed latest master from git to Amazon Linux.
Android 4.4.2, client version 0.31.0, with XPosed module.
Tried with certificate and without.

On proxy machine I start example.logTraffic, route traffic to proxy with ProxyDroid or network settings;
If proxying is enabled before client start, only Request for GetPlayer are logged, without responses. Client cannot login, no further progress. Logging in with Google account.
If proxy is enabled while client is already logged in, normal gameplay requests are sent. However no responses are coming. Client is unable to start any interaction.

I see no immediate errors in console. Is there any detailed log output to be enabled, e.g. in underlying packages?

**Comment by ELynx** [comment]
With enabled debug:
[+++] Request to /plfe/rpc
[+] Request for action GetPlayer:
{}
[<-] Request for GetPlayer  {}

[+] Waiting for response...

**Comment by rastapasta** [comment]
Indeed https://www.reddit.com/r/pokemongodev/comments/4vopt4/list_of_cloud_servers_banned_by_pokemongo_servers/

Sorry & Cheers :)

**Comment by ELynx** [comment]
OK fellow cheaters.
Since pokemon go is not about giving up, here is how I actually solved this one.
This reqires some iptables skills + some google skills.

Basic idea - hide server behind VPN, preferrably so that only server<->Nia:443 was VPNed, not whole thing.
So you need: VPN service of your choice. Pick anything, I used one with PPTP

1) set up PPTP client, as described [here](https://www.digitalocean.com/community/tutorials/vpn-pptp-ru). It is in russian, if you somehow cannot read that, google pppd call
Fight it until you have ppp0 interface
2) call ifconfig, note 2 IPs of your new ppp0. You need local IP and remote IP
3) set up ipwhatever majick as described [here](https://unix.stackexchange.com/questions/21093/output-traffic-on-different-interfaces-based-on-destination-port). I recommend creating shell script:
`#!/bin/bash`
`for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > $f; done`
`echo 1 > /proc/sys/net/ipv4/route/flush`
`ip route add default via $1 dev ppp0 table vpn-route`
`ip rule add fwmark 0x1 table vpn-route`
`iptables -A OUTPUT -t mangle -o eth0 -p tcp --dport 443 -j MARK --set-mark 1`
`iptables -A POSTROUTING -t nat -o ppp0 -p tcp --dport 443 -j SNAT --to $2`

So, go through all steps in selected answer, then call script, 1st argument is remote IP, 2nd argument is local IP. Modify script if necessary for your tables, eths whatever

4) try to telnet somewhere to ports 80 and 443. Somewhere what shows you your IP. They should be different. If your VPN output is not banned by Nia yet - viola!

Worked for me.
