### ISSUE TITLE
which file i edit for let me catch mewtwo?

### ISSUE THREAD

**Issue by darkoulis12** [rastapasta/pokemon-go-mitm-node#119]
which file i edit for let me catch mewtwo?
i want to see the mewtwo at the road and catch him which file i edit?

**Comment by bluewave41** [comment]
http://pastebin.com/7BQ7yUrk

No this won't transfer into the actual game, it's client side only. You can't get a legitimate Mewtwo using this.

**Comment by darkoulis12** [comment]
thank very much

**Comment by cptcepk** [comment]
Darkoulis12 can you help me?
