### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by zgelici** [rastapasta/pokemon-go-mitm-node#12]
Hi, this is a very nice project. But it doesnt work by me.

Server has no error
coffee example.logTraffic.coffee
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device

i installed the ca.pem on my device.

I open pokemon, but i dont see any response on the server. also i tried to run to change all pokemons.  it didnt do any actioni n the pokemon go app. 

Maby someone know how to fix it?

Thanks

**Comment by justinleewells** [comment]
Did you add the proxy to your phone?

**Comment by dylanpdx** [comment]
Also having this issue. ca.pem is on my device and the proxy is enabled. Running logTraffic gives me this: 
`[<-] Request for GetPlayer  {} 

[<-] Request for GetHatchedEggs  {} 

[<-] Request for GetInventory  {} 

[<-] Request for CheckAwardedBadges  {} 

[<-] Request for DownloadSettings  {} `

But Pokemon GO fails with "Failed to get player information from the server"

**Comment by justinleewells** [comment]
Are you logging in with PTC? Servers have been down and PTC isn't currently working.

**Comment by zgelici** [comment]
Whoops, sorry now i added proxy, only i get now the error 


HTTPS_CLIENT_ERROR on : [Error: 121052681029440:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:s3_pkt.c:1472:SSL alert number 46
121052681029440:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:s3_pkt.c:1210:

**Comment by dylanpdx** [comment]
I'm using Google logins, but it might just be the server issues then

**Comment by rastapasta** [comment]
servers down, yep - will implement some logging to make users aware that a connection issue is happening atm. refactoring to use another proxy lib atm, so better handling of connections ahead!

**Comment by R1NZLR** [comment]
Just because I've tried everything, and i'm starting to doubt myself.. 
to proxy the phone, im gonna select manual, put my computers local ip in, then use 8081 as the port?

**Comment by rubenvereecken** [comment]
@R1NZLR really do not appreciate hijackijg issues. Yes, do those steps but don't forget to install the certificate on your phone.

**Comment by R1NZLR** [comment]
My apologies. I didn't really wanna put another notch on the issue belt. I got it figured out though. Thank you.
