### ISSUE TITLE
Coffe files

### ISSUE THREAD

**Issue by cptcepk** [rastapasta/pokemon-go-mitm-node#126]
already I installed all of the tutorial, but I can not open files with the extension .coffe

**Comment by jmoriau** [comment]
Issues are not a support forum. You didnt even read the README on the front page it says:
```
Setup the CoffeeScript interpreter npm install -g coffee-script
```
You clearly have no idea what you're doing. Please stop making these issues.

**Comment by rubenvereecken** [comment]
We should add a file that github reads when people post issues with guidelines, formatting, and warnings

**Comment by jmoriau** [comment]
You should close this one as well. Also github support issue templates, but doing this would only encourage non-issues like this one. Unless maybe write something in big letters saying they can't open an issues for support on how to install node/coffeescript etc. this is not a support forum.
