### ISSUE TITLE
Any ETA for Requests API?

### ISSUE THREAD

**Issue by newhope** [rastapasta/pokemon-go-mitm-node#14]
This module is looked awesome.
But any ETA for the Requests API? Can't wait to build a web-spoof location, the existing web-spoof is just for MAC + iOS.

**Comment by rubenvereecken** [comment]
Hold on until the migration to another underlying library - hoxy - is complete, @rastapasta is finishing that today :).

**Comment by rastapasta** [comment]
its happening at https://github.com/rastapasta/pokemon-go-mitm-node/tree/hoxy right now :)

**Comment by AVVS** [comment]
@rastapasta @rubenvereecken let me know if I can help with anything as well :) Would be nice to put up a proper web client for this with pokemon discovery, walking, etc.

**Comment by rastapasta** [comment]
come and join us at https://pkre.slack.com/messages/node-mitm/ 😄 
just generate an invite here: https://shielded-earth-81203.herokuapp.com/

**Comment by rastapasta** [comment]
Oh sorry, forgot to tell you: it's all in master by now :)
