### ISSUE TITLE
Not compatible with update?

### ISSUE THREAD

**Issue by shilch** [rastapasta/pokemon-go-mitm-node#15]
Since the server update a few hours ago this proxy is not working anymore.
I get the error "HTTPS_CLIENT_ERROR on : { Error: socket hang up at ... }", so the pokemon go api does not respond, right?
There seems to be an advanced verification now that checks whether you really use a mobile phone.
Do you get the same error or is this my fault? Before the update everything worked fine.

**Comment by blackms** [comment]
I simply can't login...

**Comment by shilch** [comment]
Yep, this is what I mean. You can't login because the proxy does not respond since the server does not respond to the proxy.

**Comment by blackms** [comment]
I have some logs actually:

`
starting server for 172.217.21.42
https server started for 172.217.21.42 on 38310
starting server for 159.8.228.153
https server started for 159.8.228.153 on 33555
starting server for 54.183.13.245
https server started for 54.183.13.245 on 39392
starting server for 54.241.32.23
https server started for 54.241.32.23 on 44855
starting server for 54.241.32.2
https server started for 54.241.32.2 on 35091
starting server for 50.22.4.220
https server started for 50.22.4.220 on 44181
starting server for 169.46.12.84
https server started for 169.46.12.84 on 41364
starting server for 172.217.16.206
https server started for 172.217.16.206 on 46206
starting server for 169.46.12.72
https server started for 169.46.12.72 on 37471
starting server for 108.168.211.135
https server started for 108.168.211.135 on 46487
starting server for 216.58.212.162
https server started for 216.58.212.162 on 41327
`

But nothing else...

**Comment by shilch** [comment]
I am getting logs like these too but this are not pokemongo servers.

**Comment by blackms** [comment]
I know, 54.183.13.245 this one should be pokemon login server.

**Comment by shilch** [comment]
http://54.183.13.245 This one is from unity

**Comment by shilch** [comment]
This is a stats server for unity not pokemon go

**Comment by blackms** [comment]
We need the developer in order to fix this, it's something related to GOProto because other software are working like Bots and Map Software.

**Comment by shilch** [comment]
Yes, I can confirm that map software is working. So @rastapasta please fix the issue, I try to find it too

**Comment by blackms** [comment]
But in the end... What can you do with this?

**Comment by shilch** [comment]
😁

**Comment by rastapasta** [comment]
@shilch @blackms I can not reproduce. Everything works fine here, also on the newest version.
Please don't confuse server issues with code issues 😸  Try again!

**Comment by blackms** [comment]
@rastapasta Just a couriosity, is it possible to catch pokemon for real? I mean a different one from the one spawned by the server?

**Comment by shilch** [comment]
No, you can not get a mewtwo 😄 
I think the servers check every action, you can not spawn another pokemon.
@rastapasta I will check again.

**Comment by shilch** [comment]
no, again the same error:
```
HTTPS_CLIENT_ERROR on : { Error: socket hang up
  at TLSSocket.<anonymous> (_tls_wrap.js:816:25)
  at emitOne (events.js:101:20)
  at TLSSocket.emit (events.js:188:7)
  at Socket._handle.close (net.js:492:12)
  at Socket.g (events.js:286:16)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at TCP._handle.close [as _onclose] (net.js:492:12)
 code: 'ECONNRESET' }
```

**Comment by shilch** [comment]
Its working now.
On Android you have to use the proxy settings in wifi section and not an app like proxydroid
😄
