### ISSUE TITLE
ssl3_get_client_hello:wrong version number

### ISSUE THREAD

**Issue by MaxGriot** [rastapasta/pokemon-go-mitm-node#17]
Hello,

I get pokemongo to connect to the MITM just fine but then every HTTPS server fails with "ssl3_get_client_hello:wrong version number" any idea what could be the cause ?

Thanks,
Max

**Comment by rastapasta** [comment]
Hey hey Max, don't worry about it, its a connection unrelated to Pokemon Go that was still intercepted by the server. The HTTPs handling with the Pokemon servers works smoothly though.
Thanks for mentioning, ToDo is better logging to make the source of errors clearer.
Cheers!

**Comment by MaxGriot** [comment]
Thanks for the quick answer, I am unable to connect to pokemongo when I have the proxy enabled though, it's stuck at about 20% of the LOADING... screen's progress bar, I have the proxy enabled only for PokemonGo using ProxyDroid, maybe this isn't the right method ?

**Comment by rastapasta** [comment]
Do you get any requests logged when you use the example.logTraffic.coffee?
Will give ProxyDroid a try and tell ;)

**Comment by MaxGriot** [comment]
No I don't, every connection fails:

`[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
starting server for 54.183.13.245
https server started for 54.183.13.245 on 34834
starting server for 52.8.172.133
https server started for 52.8.172.133 on 40619
starting server for 52.9.169.220
https server started for 52.9.169.220 on 37561
starting server for 52.8.50.117
https server started for 52.8.50.117 on 41873
starting server for 54.153.13.93
https server started for 54.153.13.93 on 40657
starting server for 52.8.252.37
https server started for 52.8.252.37 on 45047
starting server for 54.183.179.134
https server started for 54.183.179.134 on 35323
starting server for 54.183.31.154
https server started for 54.183.31.154 on 40889
HTTPS_CLIENT_ERROR on : [Error: 140146002028352:error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number:s3_srvr.c:960:
]
HTTPS_CLIENT_ERROR on : [Error: 140146002028352:error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number:s3_srvr.c:960:
]
HTTPS_CLIENT_ERROR on : [Error: 140146002028352:error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number:s3_srvr.c:960:
]
HTTPS_CLIENT_ERROR on : [Error: 140146002028352:error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number:s3_srvr.c:960:
]
HTTPS_CLIENT_ERROR on : [Error: 140146002028352:error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number:s3_srvr.c:960:
]
HTTPS_CLIENT_ERROR on : [Error: 140146002028352:error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number:s3_srvr.c:960:
]
HTTPS_CLIENT_ERROR on : [Error: 140146002028352:error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number:s3_srvr.c:960:
]
HTTPS_CLIENT_ERROR on : [Error: 140146002028352:error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number:s3_srvr.c:960:
]`

**Comment by rastapasta** [comment]
I'm wondering why you only get IPs and no hostnames. This will be tricky, as the interception is looking for the specific connection to the API host. hum...

**Comment by MaxGriot** [comment]
It appears to be an issue with ProxyDroid, doing it via the wifi settings fixed the issue.
Thanks for your help :)

**Comment by rastapasta** [comment]
@MaxGriot works with ProxyDroid now ;)
