### ISSUE TITLE
Pokestop information being logged but not being changed.

### ISSUE THREAD

**Issue by ThePotato97** [rastapasta/pokemon-go-mitm-node#23]
All the data is in the terminal logs but it isn't being changed on the app
``fetched fort request { fort_id: 'c6b0d92efae8471b9f9f9e321592e946.16',
  name: 'Church of Sokcho',
  image_urls: [ 'http://lh6.ggpht.com/9sg2lBxohdoiznB3LA43CRMKG-dnUTk1Hy_9oiPaWEfneCqaAFJBX570wta_dUvgDGReqUPD4YJYuTY7CRo' ],
  type: 'CHECKPOINT',
  latitude: 38.198051,
  longitude: 128.581947,
  modifiers: [] }
[+] Current position of the player 38°11′51″N, 128°34′58″E
fetched fort request { fort_id: 'e433b81ee0c64535b6c8afd2ebd9cb02.16',
  name: 'Pagoda of Sokcho Bay',
  image_urls: [ 'http://lh5.ggpht.com/lhn6L0HUp5xI6wTau70feAcHXJuODA0xYcBTwfLMyq-fS4LcMCgcx1csY7KnD3CJtGGT_xS_H5VkbI758l-w' ],
  type: 'CHECKPOINT',
  latitude: 38.196919,
  longitude: 128.583843,
  modifiers: 
   [ { item_id: 'ITEM_TROY_DISK',
       expiration_timestamp_ms: '1469205174696',
       deployer_player_codename: 'teeruben10' } ] }
{ type: 'GOLDEEN',
  latitude: 38.19724176102549,
  longitude: 128.58304400609492,
  expirationMs: undefined,
  data: { pokemon_id: 'GOLDEEN' } }
{ type: 'KOFFING',
  latitude: 38.19749982936913,
  longitude: 128.58292855176936,
  expirationMs: undefined,
  data: { pokemon_id: 'KOFFING' } }
{ type: 'BELLSPROUT',
  latitude: 38.19695437878484,
  longitude: 128.58378522955903,
  expirationMs: undefined,
  data: { pokemon_id: 'BELLSPROUT' } }
fetched fort request { fort_id: 'e433b81ee0c64535b6c8afd2ebd9cb02.16',
  name: 'Pagoda of Sokcho Bay',
  image_urls: [ 'http://lh5.ggpht.com/lhn6L0HUp5xI6wTau70feAcHXJuODA0xYcBTwfLMyq-fS4LcMCgcx1csY7KnD3CJtGGT_xS_H5VkbI758l-w' ],
  type: 'CHECKPOINT',
  latitude: 38.196919,
  longitude: 128.583843,
  modifiers: 
   [ { item_id: 'ITEM_TROY_DISK',
       expiration_timestamp_ms: '1469205174696',
       deployer_player_codename: 'teeruben10' } ] }
{ type: 'GOLDEEN',
  latitude: 38.19724176102549,
  longitude: 128.58304400609492,
  expirationMs: undefined,
  data: { pokemon_id: 'GOLDEEN' } }
{ type: 'KOFFING',
  latitude: 38.19749982936913,
  longitude: 128.58292855176936,
  expirationMs: undefined,
  data: { pokemon_id: 'KOFFING' } }
{ type: 'BELLSPROUT',
  latitude: 38.19695437878484,
  longitude: 128.58378522955903,
  expirationMs: undefined,
  data: { pokemon_id: 'BELLSPROUT' } }
``

**Comment by rastapasta** [comment]
Using the example.replacePokeStops.coffee? If not, please copy the response handler you're using. Cheers!

**Comment by ThePotato97** [comment]
Yes, I'm using the example.replacePokeStops.coffee.

**Comment by rastapasta** [comment]
Can't reproduce - just tested with the version on master.

**Comment by ThePotato97** [comment]
Reinstalling worked.
