### ISSUE TITLE
CA generation

### ISSUE THREAD

**Issue by 7th-wonder** [rastapasta/pokemon-go-mitm-node#27]
.http-mitm-proxy/certs/ca.pem

Maybe I am just missing something really simple here, but I cannot seem to generate this certificate.

I have looked under the path but there is nothing there despite running an example and exiting out.

Thanks for any help you can provide!

**Comment by rastapasta** [comment]
It's a hidden folder, just try to do a **ls -al** to see it - if that won't help out, let me know :) Cheers!

**Comment by 7th-wonder** [comment]
Perfect, you sir are a genius. Thank you very much indeed.

**Comment by rastapasta** [comment]
With pleasure and passion! 😄 
Enjoy!
