### ISSUE TITLE
ca.pem - not generated / not working?

### ISSUE THREAD

**Issue by HypnotoadAJ** [rastapasta/pokemon-go-mitm-node#29]
Yet another rather noobish question (or issue!) in the issue section,

I cloned the project into a Linux VM, which runs pogo-optimizer just fine, and managed to execute the coffee scripts, which I understand fully. However, I'm unsure where this generated ca.pem is supposed to show up, as locate can't find any newly created ones.

Using the Pogo-Optimizer one results in a Failed Login attempt, when trying to use the hostname / ip with port 8081 as a proxy.

Any answers are appreciated, cheers.

**Comment by justinleewells** [comment]
It's located in the hidden .http-mitm-proxy/certs folder.

**Comment by HypnotoadAJ** [comment]
Thank you very much for your fast answer. I'm guessing each ca.pem needs to be generated seperately?

**Comment by justinleewells** [comment]
I believe so. You might be able to copy one to the other.

**Comment by HypnotoadAJ** [comment]
Much obliged. Got it working. Didn't think about the hidden folders. Duh.
