### ISSUE TITLE
Yes or no question!

### ISSUE THREAD

**Issue by puttichan** [rastapasta/pokemon-go-mitm-node#35]
"Setup your connection to use your machine as a proxy (default port is 8081)"

This part means go to your Wifi and set proxy as your ip address from "whatsmyipaddress.com" onto SERVER and port as in 8081 with authentication.

Right?

**Comment by justinleewells** [comment]
No, you need to put your inside/private ip address, not your public one. The one that you get from network settings.

**Comment by puttichan** [comment]
@justinleewells 
Ok, thanks!
Also, after I set up the whole process, do you know how to start this?
I opened up a terminal and just put "coffee alwaysSuperThrow.coffee."
Is this the right way?

**Comment by justinleewells** [comment]
Correct. Make sure to install coffeescript with `npm install -g coffee-script`

**Comment by puttichan** [comment]
@justinleewells 
I am sorry for asking more questions, but do you know why this might have happened?

I installed NodeMITMProxyCA and put my WIFI IP Address onto the SERVER with the PORT 8081 and typed "coffee alwaySuperThrow.coffee" then this give me this error.

"[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
[-] HTTP_SERVER_ERROR on :
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8081
  at Object.exports._errnoException (util.js:873:11)
  at exports._exceptionWithHostPort (util.js:896:20)
  at Server._listen2 (net.js:1250:14)
  at listen (net.js:1286:10)
  at Server.listen (net.js:1382:5)
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:86:23
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/ca.js:132:12
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:726:13
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:52:16
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:269:32
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:44:16
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:723:17
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:167:37
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/ca.js:192:12
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:52:16
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:550:17
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:544:17
  at _arrayEach (/Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:85:13)
  at Immediate.taskComplete (/Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:543:13)
  at processImmediate [as _immediateCallback] (timers.js:383:17)"

**Comment by justinleewells** [comment]
You must already have another program that is listening on that port.

**Comment by puttichan** [comment]
@justinleewells 
Oh shit, I might.
Will changing the port to sth like 8082 work? :O

**Comment by justinleewells** [comment]
It should, as long as you don't have something listening on that one too ;)

**Comment by puttichan** [comment]
@justinleewells 

Same error after changing port from 8081 to 8082 on HTTP PROXY.
Urgh, almost there, but just dont know how to approach it...

"[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
[-] HTTP_SERVER_ERROR on :
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8081
  at Object.exports._errnoException (util.js:873:11)
  at exports._exceptionWithHostPort (util.js:896:20)
  at Server._listen2 (net.js:1250:14)
  at listen (net.js:1286:10)
  at Server.listen (net.js:1382:5)
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:86:23
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/ca.js:132:12
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:726:13
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:52:16
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:269:32
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:44:16
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:723:17
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:167:37
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/ca.js:192:12
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:52:16
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:550:17
  at /Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:544:17
  at _arrayEach (/Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:85:13)
  at Immediate.taskComplete (/Users/Hong/Downloads/pokemon-go-mitm-node/node_modules/http-mitm-proxy/node_modules/async/lib/async.js:543:13)
  at processImmediate [as _immediateCallback] (timers.js:383:17)"

**Comment by puttichan** [comment]
@justinleewells 
Do I need to set proxy on my mac or my ipad with Pokemon Go?
