### ISSUE TITLE
PROXY_TO_SERVER_REQUEST_ERROR: Error: socket hang up

### ISSUE THREAD

**Issue by VirenMohindra** [rastapasta/pokemon-go-mitm-node#39]
I seem to be getting this error whenever I try to launch an example. I've added the proxy, certs, but I receive 

`PROXY_TO_SERVER_REQUEST_ERROR: Error: socket hang up` whenever I open up localhost:8081 on my MacBook. Everything was installed correctly.

**Comment by Orkeren** [comment]
You're not supposed to open localhost:8081 on your MacBook. You're supposed to add your MacBook as a proxy server to your Android/iPhone.
