### ISSUE TITLE
Not getting inventory data for pokemon

### ISSUE THREAD

**Issue by queso** [rastapasta/pokemon-go-mitm-node#4]
I turned on `debug: true` when starting MITM.

Getting this:

```
[+] Response for action GetInventory
{ success: true,
  inventory_delta:
   { original_timestamp_ms: '1468961850688',
     new_timestamp_ms: '1468961850688',
     inventory_items: [] } }
[!] Overwriting GetInventory
```

**Comment by rastapasta** [comment]
Thank's for spotting - inventory gets requested with a timestamp of last query. only things that changed will be included in the delta. take a look @ login process, you will spot the full set :)
I also recommend checking out example.replacePokemons - Cheers!
