### ISSUE TITLE
npm install failed, node-protobuf@1.3.2 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by kmcheung12** [rastapasta/pokemon-go-mitm-node#42]
Ran into issue on Mac El Capitan when doing:

`npm install`

    > node-protobuf@1.3.2 install /Users/kmc/code/pokemon-go-mitm-node/node_modules/node-protobuf
    > node-gyp rebuild
    
    lp.sh: line 2: pkg-config: command not found
    gyp: Call to 'sh lp.sh' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit     (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
    gyp ERR! System Darwin 15.5.0
    gyp ERR! command "/usr/local/Cellar/node/6.2.1/bin/node"     "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/kmc/code/pokemon-go-mitm-node/node_modules/node-protobuf
    gyp ERR! node -v v6.2.1
    gyp ERR! node-gyp -v v3.3.1
    gyp ERR! not ok
    npm ERR! Darwin 15.5.0
    npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.2.1
    npm ERR! npm  v3.9.3
    npm ERR! code ELIFECYCLE
    
    npm ERR! node-protobuf@1.3.2 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the node-protobuf@1.3.2 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the node-protobuf package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs node-protobuf
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls node-protobuf
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/kmc/code/pokemon-go-mitm-node/npm-debug.log

The reason is that there is a dependency on `pkg-config` not checked by build script.
The issue is solved by `brew install pkg-config` prior to `npm install`
Thought it might be useful to someone

**Comment by rastapasta** [comment]
Thanks for the  info, adding it to the readme!

**Comment by valyard** [comment]
I'm getting the same error but I have pkg-config installed.
brew install pkg-config
Warning: pkg-config-0.29.1_1 already installed

**Comment by valyard** [comment]
ok, need to actually install protobuf first
`brew install --devel protobuf`
