### ISSUE TITLE
Ability to close proxy/port

### ISSUE THREAD

**Issue by BradlySharpe** [rastapasta/pokemon-go-mitm-node#43]
Could the ability to close the proxy be added?

I'm trying to create multiple proxies however it doesn't look like the ports are closed until the node app is closed?

I've tested with:
```
var proxy = new (require('http-mitm-proxy'));
proxy.listen({port: 9000});
// test port is open with telnet
proxy.close();
// test port is closed with telnet
```

There doesn't seem to be the ability of closing the proxy? I've tried adding a close proxy function however it doesn't seem to work either, not sure if I was doing it right.

```
setupProxy: ->
    proxy = new Proxy()
    ...
    @closeProxy = proxy.close
    ...
```

**Comment by rastapasta** [comment]
Thanks for noticing :)

**Comment by BradlySharpe** [comment]
No worries, thanks for the quick fix/reply
