### ISSUE TITLE
Ssl handshake failure

### ISSUE THREAD

**Issue by ksemeks** [rastapasta/pokemon-go-mitm-node#5]
Hi,

I imported ca.pem, but when I try to log in into pokemongo I can't, and I get this error:

`
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
starting server for single.upsight-api.com
https server started for single.upsight-api.com on 59640
starting server for pgorelease.nianticlabs.com
https server started for pgorelease.nianticlabs.com on 59642
starting server for android.clients.google.com
https server started for android.clients.google.com on 59651
HTTPS_CLIENT_ERROR on : Error: 140735193022464:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 46
140735193022464:error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:1210:

  at Error (native)

`

**Comment by rubenvereecken** [comment]
Got this here from somewhere on SO

> You get the error about certificate unknown from the server, so it refers to the validation of your client certificate on the server side and not to the (successful) validation of the servers certificate at the client side. That means the server does not like your client certificate.

I propose we change it so that only niantic gets mitm'd.

**Comment by ksemeks** [comment]
Still remains the problem that I can't login using that certificate. Maybe cert problem?

**Comment by rubenvereecken** [comment]
This is actually the client certificate failing and it doesn't show which client (pgo or another service?) sadly, or does it further down the log? Make sure you set up the proxy first, then the app.

**Comment by ksemeks** [comment]
Every client gives an error, sooner or later. If i keep it running, I see just errors. 

The device and cert are setted correctly AFAIK. 
Can I maybe try with some other certs or something?

**Comment by rastapasta** [comment]
How are things with the current version on master? Cheers!

**Comment by ksemeks** [comment]
Working now

**Comment by rastapasta** [comment]
Wonderful!
