### ISSUE TITLE
Getting a pokemon with that ?

### ISSUE THREAD

**Issue by LeaklessGfy** [rastapasta/pokemon-go-mitm-node#50]
Hello,

When you say release a pokemon it mean getting it ?  if not, your tool can allow us to get special pokemon ?

Another question,
Is it risky to use ? Thanks :)

**Comment by prajwalkman** [comment]
Release means transferring, i.e., deleting. You can't get back a pokemon once you delete it.

**Comment by rastapasta** [comment]
@LeaklessGfy you could trigger a Pokemon encounter as soon as there is one nearby, catching it via craftRequest calls - but it will be the exact same pokemon that you could have catched by yourself by using the app.

At the risk to use: any non-altering things (= watching the traffic) should be undetectable (as long as you set up the certificate). any request altering *could* be detected, as its still unknown if some fields in the RequestEnvelope could be checksums of some sort. We can't say yet for sure but its a big topic in the reverse engineering scene atm.

**Comment by LeaklessGfy** [comment]
Thanks a lot !
