### ISSUE TITLE
Certificates and Keys not generated on Raspberry Pi

### ISSUE THREAD

**Issue by ilendemli** [rastapasta/pokemon-go-mitm-node#57]
I am trying to run this on my Raspberry Pi, the server starts and listens on the port. Unfortunatly the certs and keys folders are empty, so I can't install the cert on my phone. Is there a fix or workaround known?

**Comment by rastapasta** [comment]
Hey @ilendemli, you can manually create the certificate with following two commands:
```
openssl genrsa -out .http-mitm-proxy/keys/ca.private.key 2048`
openssl req -x509 -new -nodes -key .http-mitm-proxy/keys/ca.private.key -days 1024 -out .http-mitm-proxy/certs/ca.pem -subj "/C=US/ST=Utah/L=Provo/O=PokemonCA/CN=example.com"
```
Hope that helps! Cheers!

**Comment by ilendemli** [comment]
Thanks! I used following commands:

openssl genrsa -out .http-mitm-proxy/keys/ca.private.key 2048
openssl rsa -in .http-mitm-proxy/keys/ca.private.key -pubout > .http-mitm-proxy/keys/ca.public.key
openssl req -x509 -new -nodes -key .http-mitm-proxy/keys/ca.private.key -days 1024 -out .http-mitm-proxy/certs/ca.pem -subj "/C=US/ST=Utah/L=Provo/O=PokemonCA/CN=example.com"
