### ISSUE TITLE
Extreme Noob alert-failure to run

### ISSUE THREAD

**Issue by millejosh** [rastapasta/pokemon-go-mitm-node#7]
So I've successfully installed everything including the CA cert but after I start HTTP server I'm completely lost.  Does the "How to code it" section go into coffee/terminal or should i be able to start  a localhost to view traffic?

**Comment by millejosh** [comment]
this is all I'm seeing

coffee> PokemonGoMITM = require './lib/pokemon-go-mitm'
[Function: PokemonGoMITM]
coffee> server = new PokemonGoMITM port: 8081
[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
PokemonGoMITM {
  handleProxyError: [Function],
  handleProxyRequest: [Function],
  port: 8081,
  debug: false }
coffee> starting server for pgorelease.nianticlabs.com
https server started for pgorelease.nianticlabs.com on 61674
starting server for accounts.google.com
https server started for accounts.google.com on 61679

**Comment by eratio08** [comment]
The how to code and the examples show you how to use the api of this project.
https://github.com/justinleewells/pogo-optimizer i.e. uses the pogo-mitm proxy to get the pokemon an calculates their stats.
If you dont want to code - use the examples or try pogo-optimizer.

**Comment by millejosh** [comment]
Well that makes me feel dumb. I got everything sorted out. Thanks for the help!
