### ISSUE TITLE
Trying to spawn a MewTwo

### ISSUE THREAD

**Issue by blackms** [rastapasta/pokemon-go-mitm-node#72]
I made this script:
`PokemonGoMITM = require './lib/pokemon-go-mitm'

server = new PokemonGoMITM port: 8081
  # Parse the wild pokemons nearby
  .addResponseHandler "GetMapObjects", (data) ->
    return false if not data.map_cells.length

    for cell in data.map_cells
      if cell.catchable_pokemons.length > 0
        first_pokemon = cell.catchable_pokemons[0]
        cell.catchable_pokemons[0].pokemon_id = 'MEWTWO'
        console.log('Altered cell.catchable_pokemons')
        console.log(cell.catchable_pokemons[0])
        for nearby in cell.nearby_pokemons
          if nearby.encounter_id == first_pokemon.encounter_id
            nearby.pokemon_id = 'MEWTWO'
            console.log('Altered Neraby pokemons')
            console.log(nearby)
            console.log('Wild pokemon: ')
            cell.wild_pokemons[0].pokemon_data.pokemon_id = 'MEWTWO'
            console.log(cell.wild_pokemons[0])
    data`

But client side I didn't see any mewtwo, some idea?

**Comment by caspaas** [comment]
How did you manage it eventually?
