### ISSUE TITLE
Scripts not working?

### ISSUE THREAD

**Issue by caspaas** [rastapasta/pokemon-go-mitm-node#74]
I used the crt from https://github.com/justinleewells/pogo-optimizer
Because when It generated I cant seem to see the "generated" pem.

Everything was installed and it says PokemonGo MITM proxy listening
I can even sign into pokemon go
But none of the scripts are working for me.

Running it on Linux Lite 3.0
Made 2 machines and tried this.
The ca.pem doesnt get generated at all

**Comment by ext4t1c0** [comment]
same prob, same os here

**Comment by rastapasta** [comment]
@ilendemli [solved his issue](https://github.com/rastapasta/pokemon-go-mitm-node/issues/57) by generating it manually:
```
openssl genrsa -out .http-mitm-proxy/keys/ca.private.key 2048
openssl rsa -in .http-mitm-proxy/keys/ca.private.key -pubout > .http-mitm-proxy/keys/ca.public.key
openssl req -x509 -new -nodes -key .http-mitm-proxy/keys/ca.private.key -days 1024 -out .http-mitm-proxy/certs/ca.pem -subj "/C=US/ST=Utah/L=Provo/O=PokemonCA/CN=example.com"
```
give it a try :)

**Comment by rastapasta** [comment]
Also, as a recommendation if you are running the latest version on a rooted Android, you can use [pokemon-go-xposed](https://github.com/rastapasta/pokemon-go-xposed) to get around all certificate issues at once :)

**Comment by blink701** [comment]
How do I know if I'm connected to the script or not? Because I've tried doing it, I'm able to go on pokemon go but none of the scripts work for me? I have the xposed module installed too.

**Comment by ilendemli** [comment]
@blink701 i would try running the logTraffic example and see if any traffic goes through, if not, then there are some issues with your settings, thats how i do

**Comment by caspaas** [comment]
im so sorry rastapasta i didnt see it was already solved.

On a side note whenever i try the xposed version it doesnt want to login very well,
But with the xposed pokemon go you supply. you dont have to install the mitm certificate at all ?
Or am i reading this wrong?

**Comment by breakmyapple** [comment]
hey guys great work.
but I'm having trouble installing the cert, it keeps saying cannot install profile due to an unknown error ?
it works fine with https://github.com/justinleewells/pogo-optimizer 
I'm on ios i use the ssl kill switch 2 to by pass the ssl pinning

**Comment by caspaas** [comment]
does this need to be done as well?
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080

Because everything is set up.
proxy. everything. Certificate.
But it doest really do anything at all when connecting and when i log in....

**Comment by trisk** [comment]
@caspaas are you sure you're not just missing the cert  because `.http-mitm-proxy` is a "hidden" directory?

You don't need to install the cert if you disabled cert pinning (though if you set the proxy globally for your phone other apps might not work without the cert).

**Comment by caspaas** [comment]
Well I converted the Cert. with a fix provided here.
installed it. done.
set my proxy in my phone wifi to my local IP/linux device port 8081.
but alas no avail. 
Nothing happens 

Pogo Optimizer does work tho. but this just.. does not

**Comment by fny** [comment]
I'm having no issues using the Xposed module without supplying a certificate. The only trick is that I have to sign in before enabling the tunnel.

**Comment by caspaas** [comment]
@fny Then how did you set it up.
Isnt there a clearer version of the guide?

Phone is rooted. Xposed modules installed.
Using pokemon GO latest.

Linux system installed.
did every step

eventually doing the command coffee example.changeLevel.coffee
PokemonGO MITM PROXY listening on 8081.

But nothing happens at all.

**Comment by trisk** [comment]
@caspass pogo-optimizer runs the same proxy so that's really strange. Did you stop pogo-optimizer before starting the script? Did you try the logTraffic example?

Also try toggling airplane mode on your phone; mine would disable the proxy if it wasn't available at the time it connects to wifi or the network.

**Comment by caspaas** [comment]
@trisk ofcourse I did.
but I tested the pogo-optimizer on my other system. (Windows with Docker) very easy and done.

Yeah I did. 
its like it never connects at all with my Linux Lite 3.0

**Comment by trisk** [comment]
Since it works on one machine but not the other you probably have a firewall rule or some network misconfiguration blocking connections.

**Comment by caspaas** [comment]
@trisk I checked my router for everything.
Firewalls disabled everywhere.
Also linux lite 3 doesnt even have a firewall.

What OS are you using if I may ask? Ubuntu?

**Comment by caspaas** [comment]
I think Ive found my issue.... worst mistake ever.
Firewall was left on somewhere somehow.. omg im so sorry guys..

**Comment by breakmyapple** [comment]
this is what I'm getting returned now :Error: EACCES: permission denied, open '/home/jay/pokemon-go-mitm-node/.http-mitm-proxy/certs/p45-ckdevice.icloud.com.pem'

which cert am i looking for in .http-mitm-poxy ?
thanks for the help guys
