### ISSUE TITLE
example.alwaySuperThrow.coffee error while loading now

### ISSUE THREAD

**Issue by caspaas** [rastapasta/pokemon-go-mitm-node#79]
Almost every script works

But this one seems to fail when loading.

It just crashes.

**Comment by trisk** [comment]
What's the error?

**Comment by caspaas** [comment]
@trisk 
[-] HTTPS_CLIENT_ERROR on :
[+++] Request to /plfe/rpc
[+] Request for action GetPlayer: 
and the throws are not super.
