### ISSUE TITLE
how to run in mac?

### ISSUE THREAD

**Issue by Jake1test122** [rastapasta/pokemon-go-mitm-node#80]
hey, i have a mac, and i have mitm proxy installed and coffee on my mac, how do i get the proxy to run on my mac? and i cant download the ca cert from the link, it says error, and how do i switch the port to 8081 on my mac, can someone help me?

**Comment by trisk** [comment]
Just `coffee whatever.coffee` to run a script, which will start the proxy. The cert is in the location in the README and created after it starts.

**Comment by Jake1test122** [comment]
thanks!
