### ISSUE TITLE
(ubuntu) help in tutorial

### ISSUE THREAD

**Issue by Poootaatoooo** [rastapasta/pokemon-go-mitm-node#81]
i'm new to a lot of this, but I wanna experiment with this, I've gotten to this part in the tutorial:

> Run and quit one of the examples once to get a CA certificate generated
coffee example.logTraffic.coffee

>Copy the generated .http-mitm-proxy/certs/ca.pem to your mobile
Add it to the "trusted certificates"
Setup your connection to use your machine as a proxy (default port is 8081)
Enjoy 

I ran `coffee example.logTraffic.coffee` and it displayed 

> [+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device

and then exited it like the tutorial said, but the next part has me stumped,

>Copy the generated .http-mitm-proxy/certs/ca.pem to your mobile
Add it to the "trusted certificates"
Setup your connection to use your machine as a proxy (default port is 8081)

where is the generated certificate located, and what does it mean by "add it to the 'trusted certificates' ", and after that's done, how do i set up the proxy

I'm using the xposed module on the newest version of the app on android 6.0.1, if that makes a difference

(also, can you log in with a google account with this or just ptc? is there a way to use google, because thats what my main account is :/)

thanks!

**edit:**
http://i.imgur.com/iv3Veq1.png is this the right directory? theres no certs folder...

**Comment by Poootaatoooo** [comment]
http://i.imgur.com/iv3Veq1.png is this the right directory? theres no certs folder...

**Comment by trisk** [comment]
The directory is named exactly what it says in the instructions, `.http-mitm-proxy`. Your file manager is probably hiding it from you. Import the certificate file in your phone's security settings and configure the proxy address for your wifi or mobile connection.

**Comment by ilendemli** [comment]
If you have the xposed module, then you don't have to install it on your phone. but there still has to be a certificate generated on the server (i think). the .http-mitm-proxy is as @trisk said, hidden. if the script isn't generating them for you, then use the [these](https://github.com/rastapasta/pokemon-go-mitm-node/issues/57) commands to generate one and then try running it again

**Comment by JokerCPP** [comment]
use control+h on the directory to see hidden folders.

**Comment by Poootaatoooo** [comment]
Thanks everyone for responding,now I have the certificate installed on my phone, but I'm having trouble connecting through the proxy... Do I just connect through [my IP address]:8081? Because when I tried that, the internet stayed working, but pokemon go gave me an authentication error on PTC and the "servers are humbled by your incredible response" message when I tried google, I checked go.jooas.com and nothing was down, so am I doing something wrong?

**Comment by Poootaatoooo** [comment]
i got it working now
