### ISSUE TITLE
Cannot find module 'pokemongo-protobuf'

### ISSUE THREAD

**Issue by smile437** [rastapasta/pokemon-go-mitm-node#86]
When i try launch coffee script i have an error but i had install protobuf
[ScreenShot of terminal](http://joxi.ru/52anZ60Ud9lbA0) Whats the problem?

**Comment by hillerstorm** [comment]
seems like you missed running `npm install` first?

**Comment by smile437** [comment]
Oh really, now its work. Would you help me one more. Where this certificate location on my mac and how put it to iphone

**Comment by rastapasta** [comment]
Please read the README, the path is given there - just send the file to yourself via email and open it. Cheers!
