### ISSUE TITLE
Anyone know where candy_cost values can be found?

### ISSUE THREAD

**Issue by johyphenel** [rastapasta/pokemon-go-mitm-node#87]
Can't seem to find candy_cost in any of the logged responses.

I'm trying to set up a script to rename pokemon with their iv values && the number of evolutions possible. Was hoping this value would be sent with one of the responses: https://github.com/AeonLucid/POGOProtos/blob/3682394bf5c10ac5ebdfcb06cd7f0f7479afc7a5/src/POGOProtos/Settings/Master/PokemonUpgradeSettings.proto#L7

**Comment by trisk** [comment]
It's possible that the app only sends a DownloadItemTemplates request on login, or that there are internal templates in the app which the server does not have new versions of.

**Comment by trisk** [comment]
`candy_to_evolve` is also a field in PokemonSettings which can be part of the DownloadItemTemplates response.

**Comment by johyphenel** [comment]
Might just never get sent - I mitm'ed from the fresh start and didn't log any of these values in the response. I guess it's not too hard to create a map for the ones I really care about.
