### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by BeginnerSlob** [rastapasta/pokemon-go-mitm-node#88]
i got an error when "npm install"

`163 error Error: spawn ENOMEM`
`163 error     at errnoException (child_process.js:988:11)`
`163 error     at ChildProcess.spawn (child_process.js:935:11)`
`163 error     at exports.spawn (child_process.js:723:9)`
`163 error     at exports.execFile (child_process.js:607:15)`
`163 error     at /usr/share/npm/lib/cache.js:470:7`
`163 error     at /usr/lib/nodejs/which.js:55:18`
`163 error     at Object.oncomplete (fs.js:107:15)`
`164 error If you need help, you may report this log at:`
`164 error     <http://github.com/isaacs/npm/issues>`
`164 error or email it to:`
`164 error     <npm-@googlegroups.com>`
`165 error System Linux 3.4.0+`
`166 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"`
`167 error cwd /root/pokemon-go-mitm-node`
`168 error node -v v0.10.25`
`169 error npm -v 1.3.10`
`170 error syscall spawn`
`171 error code ENOMEM`
`172 error errno ENOMEM`

**Comment by BeginnerSlob** [comment]
and i use the TAOBAO npm mirror http://npm.taobao.org
Does it cause the error?

**Comment by hillerstorm** [comment]
`error Error: spawn ENOMEM` seems like you're running out of memory?

**Comment by BeginnerSlob** [comment]
So how do i solve this error?

**Comment by BeginnerSlob** [comment]
uh, i found that i use node-v0.10.25, does it cause the error?

**Comment by trisk** [comment]
Does your computer have enough free memory to run Node?

**Comment by BeginnerSlob** [comment]
how much memory does Node need? although i just have 600M free memory..

**Comment by BeginnerSlob** [comment]
when i update my node version, there is a new error like this:
![1](https://cloud.githubusercontent.com/assets/1858088/17369216/014d448e-59ca-11e6-816e-b0900d7a1336.png)

**Comment by trisk** [comment]
Are you using Cygwin or the Windows 10 Linux runtime? Your install is missing the `pkg-config` tool.

**Comment by BeginnerSlob** [comment]
thx for @trisk 's help, i solved this error. But i get another error when run 'coffee example.logTraffic.coffee'. There is the log below:
![2](https://cloud.githubusercontent.com/assets/1858088/17373955/0ab1b4a2-59dd-11e6-8bff-89469575091a.jpg)

**Comment by BeginnerSlob** [comment]
when i change the Node version to the new stable(not 0.xx.xx) and reinstall the repo('npm uninstall' and 'npm install'), i solve this, now i can enjoy it, thank you all! :)
