### ISSUE TITLE
Copy the generated .http-mitm-proxy/certs/ca.pem to your mobile Add it to the "trusted certificates"

### ISSUE THREAD

**Issue by darkoulis12** [rastapasta/pokemon-go-mitm-node#89]
Copy the generated .http-mitm-proxy/certs/ca.pem to your mobile
Add it to the "trusted certificates"

how i do this??
how i copy in my mobile?where i copy it?and where i put it?

**Comment by trisk** [comment]
You can share it with Google Drive or email it to yourself.
Follow https://support.google.com/nexus/answer/2844832?hl=en and choose "VPN and apps" if prompted.

**Comment by darkoulis12** [comment]
and where i run the commands sir?
