### ISSUE TITLE
How to generate ca.pem

### ISSUE THREAD

**Issue by smile437** [rastapasta/pokemon-go-mitm-node#92]
i launched script, where i can find generated certificate? Or what i need to do to create it?
PS I have iPhone

**Comment by wellart** [comment]
coffee example.logTraffic.coffee
since android not accept .pem you must change to .crt
here how to change "openssl x509 -outform der -in ca.pem -out ca.crt" without quoyte

**Comment by trisk** [comment]
@wellart Android accepts the cert without converting.

**Comment by smile437** [comment]
@wellart 
@trisk 
i have iphone guys

**Comment by trisk** [comment]
I think you just click the file on iOS to install it.

**Comment by smile437** [comment]
@trisk Where i can find it on my mac? in folder -- http-mitm-proxy i havent folder -- certs or some file with *.pem

**Comment by XxBockesxX** [comment]
Open Terminal found in Finder > Applications > Utilities
In Terminal, paste the following: defaults write com.apple.finder AppleShowAllFiles YES
Press return
Hold the ‘Option/alt’ key, then right click on the Finder icon in the dock and click Relaunch.
Go to the pokemon-go-mitm-node folder and you will now have the folder, it is hidden by default.

**Comment by rastapasta** [comment]
Thanks for helping each other 👍
