### ISSUE TITLE
All issues

### ISSUE THREAD

**Issue by Sapphireflames** [rastapasta/pokemon-go-mitm-node#93]
Used every version of windows 64 bit capable things to compile and run this module and nothing works. 

It can't find it's nan, it has no idea where anything is, it looks at E: for everything, it shows every error in existence and I don't understand why. 
I've followed loads of tutorials but it's just not happy. I'm seeing all of the issues shown in these issue posts.

**Comment by caspaas** [comment]
Thats because windows is a hard one to work with for this.
Try Linux/ubuntu its easier.

**Comment by rastapasta** [comment]
@Sapphireflames your might find help here https://github.com/rastapasta/pokemon-go-mitm-node/issues/1 - there are pre-compiled libraries linked
